/**
 * AI IQ Questions - from ai_questions.csv (first 15 AI_IQ questions)
 */
import type { DiagnosticQuestion } from './types';

export const AI_IQ_QUESTIONS: DiagnosticQuestion[] = [
  {
    id: 'AIQ_01',
    assessment_type: 'AI_IQ',
    domain: 'Deployment',
    question_text: 'Does your organization currently use AI tools?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Experimentally', score: 5 },
      { label: 'In multiple teams', score: 12 },
      { label: 'Embedded across operations', score: 20 },
    ],
  },
  {
    id: 'AIQ_02',
    assessment_type: 'AI_IQ',
    domain: 'Deployment',
    question_text: 'In how many functional areas is AI currently deployed?',
    response_type: 'multiple_choice',
    options: [
      { label: '0 areas', score: 0 },
      { label: '1 area', score: 4 },
      { label: '2-3 areas', score: 12 },
      { label: '4+ areas', score: 20 },
    ],
  },
  {
    id: 'AIQ_03',
    assessment_type: 'AI_IQ',
    domain: 'Deployment',
    question_text: 'Are any AI systems customer-facing or public?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Internal only', score: 5 },
      { label: 'Limited customer-facing', score: 12 },
      { label: 'Multiple customer channels', score: 20 },
    ],
  },
  {
    id: 'AIQ_04',
    assessment_type: 'AI_IQ',
    domain: 'Integration',
    question_text: 'Are AI tools connected to your CRM or core business systems?',
    response_type: 'multiple_choice',
    options: [
      { label: 'Not connected', score: 0 },
      { label: 'Manual exports/imports', score: 6 },
      { label: 'Some integrations', score: 12 },
      { label: 'Directly integrated', score: 20 },
    ],
  },
  {
    id: 'AIQ_05',
    assessment_type: 'AI_IQ',
    domain: 'Integration',
    question_text: 'Are AI outputs stored and reusable in your systems?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Occasionally', score: 7 },
      { label: 'Usually', score: 14 },
      { label: 'Systematically', score: 20 },
    ],
  },
  {
    id: 'AIQ_06',
    assessment_type: 'AI_IQ',
    domain: 'Integration',
    question_text: 'Do AI tools pull from internal data sources or knowledge bases?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Rarely', score: 5 },
      { label: 'Some systems do', score: 12 },
      { label: 'Most important systems do', score: 20 },
    ],
  },
  {
    id: 'AIQ_07',
    assessment_type: 'AI_IQ',
    domain: 'Revenue',
    question_text: 'Does AI directly support lead generation or revenue operations?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Indirectly only', score: 6 },
      { label: 'Some contribution', score: 12 },
      { label: 'Clear measurable contribution', score: 20 },
    ],
  },
  {
    id: 'AIQ_08',
    assessment_type: 'AI_IQ',
    domain: 'Revenue',
    question_text: 'Can you tie any AI activity to measurable business KPIs?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Loosely', score: 7 },
      { label: 'Partially', score: 14 },
      { label: 'Clearly and consistently', score: 20 },
    ],
  },
  {
    id: 'AIQ_09',
    assessment_type: 'AI_IQ',
    domain: 'Revenue',
    question_text: 'Is AI used in any revenue-critical workflow (sales/conversion/retention)?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Limited test', score: 7 },
      { label: 'One key workflow', score: 14 },
      { label: 'Multiple key workflows', score: 20 },
    ],
  },
  {
    id: 'AIQ_10',
    assessment_type: 'AI_IQ',
    domain: 'Automation',
    question_text: 'Do AI tools trigger follow-up actions automatically?',
    response_type: 'multiple_choice',
    options: [
      { label: 'Never', score: 0 },
      { label: 'Sometimes', score: 7 },
      { label: 'Often', score: 14 },
      { label: 'Core operating behavior', score: 20 },
    ],
  },
  {
    id: 'AIQ_11',
    assessment_type: 'AI_IQ',
    domain: 'Automation',
    question_text: 'Are multiple tools connected via Zapier/Make/API/native automations?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Minimal', score: 6 },
      { label: 'Moderate', score: 12 },
      { label: 'Extensive', score: 20 },
    ],
  },
  {
    id: 'AIQ_12',
    assessment_type: 'AI_IQ',
    domain: 'Automation',
    question_text: 'Are there multi-step AI workflows in place?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Very limited', score: 5 },
      { label: 'Some', score: 12 },
      { label: 'Multiple repeatable flows', score: 20 },
    ],
  },
  {
    id: 'AIQ_13',
    assessment_type: 'AI_IQ',
    domain: 'Oversight',
    question_text: 'Do you have internal guidelines for AI use?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Informal only', score: 7 },
      { label: 'Partial written', score: 14 },
      { label: 'Clear documented standards', score: 20 },
    ],
  },
  {
    id: 'AIQ_14',
    assessment_type: 'AI_IQ',
    domain: 'Oversight',
    question_text: 'Are important AI outputs reviewed by humans?',
    response_type: 'multiple_choice',
    options: [
      { label: 'Never', score: 0 },
      { label: 'Rarely', score: 5 },
      { label: 'Sometimes', score: 12 },
      { label: 'Always (high-impact cases)', score: 20 },
    ],
  },
  {
    id: 'AIQ_15',
    assessment_type: 'AI_IQ',
    domain: 'Oversight',
    question_text: 'Is anyone explicitly responsible for AI oversight?',
    response_type: 'multiple_choice',
    options: [
      { label: 'No', score: 0 },
      { label: 'Informally', score: 6 },
      { label: 'Partially assigned', score: 12 },
      { label: 'Clearly assigned', score: 20 },
    ],
  },
];
