import { useEffect, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { DiagnosticResults } from "@/anydoor/DiagnosticResults";
import { normalizeReportPathToken } from "@/anydoor/lib/diagnosticShare";
import {
  getProspectByPublicAccess,
  getProspectByShareToken,
  isProspectRowUuid,
  prospectRowToDiagnosticResult,
} from "@/anydoor/lib/supabaseProspect";
import type { DiagnosticResult } from "@/anydoor/DiagnosticForm";

/**
 * Public shared report:
 * - Permanent: `/report/{prospect_uuid}?k={report_access_key}` (RPC get_prospect_by_public_access)
 * - Legacy: `/report/{share_token}` (RPC get_prospect_by_share_token)
 */
export default function SharedReportPage() {
  const { token: tokenParam } = useParams<{ token: string }>();
  const [searchParams] = useSearchParams();
  const normalizedToken = tokenParam ? normalizeReportPathToken(tokenParam) : "";
  const accessKey = searchParams.get("k")?.trim() ?? "";
  const incompletePermanentLink = Boolean(normalizedToken && isProspectRowUuid(normalizedToken) && !accessKey);

  const [result, setResult] = useState<DiagnosticResult | null>(null);
  const [submittedUrl, setSubmittedUrl] = useState("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    if (!normalizedToken || incompletePermanentLink) return;

    setResult(null);
    setSubmittedUrl("");
    (async () => {
      setError(null);
      const row =
        isProspectRowUuid(normalizedToken) && accessKey
          ? await getProspectByPublicAccess(normalizedToken, accessKey)
          : await getProspectByShareToken(normalizedToken);
      if (cancelled) return;
      if (!row) {
        setError("Report not found or link expired.");
        return;
      }
      const r = prospectRowToDiagnosticResult(row);
      if (!r) {
        setError("Could not load this report.");
        return;
      }
      setResult(r);
      setSubmittedUrl(typeof row.url === "string" ? row.url : "");
    })();

    return () => {
      cancelled = true;
    };
  }, [normalizedToken, accessKey, incompletePermanentLink]);

  if (!normalizedToken) {
    return (
      <div className="min-h-screen px-4 py-16 text-center" style={{ backgroundColor: "#07080d", color: "#e8eef5" }}>
        <p className="text-white/70">Invalid link.</p>
        <Link to="/doors/url-diagnostic" className="mt-6 inline-block text-[#c9973a] underline">
          Run a new diagnostic →
        </Link>
      </div>
    );
  }

  if (incompletePermanentLink) {
    return (
      <div className="min-h-screen px-4 py-16 text-center" style={{ backgroundColor: "#07080d", color: "#e8eef5" }}>
        <p className="text-white/70">
          This report link is incomplete. Use the full link from your diagnostic (including the security key).
        </p>
        <Link to="/doors/url-diagnostic" className="mt-6 inline-block text-[#c9973a] underline">
          Run a new diagnostic →
        </Link>
      </div>
    );
  }

  if (error && !result) {
    return (
      <div className="min-h-screen px-4 py-16 text-center" style={{ backgroundColor: "#07080d", color: "#e8eef5" }}>
        <p className="text-white/70">{error}</p>
        <Link to="/doors/url-diagnostic" className="mt-6 inline-block text-[#c9973a] underline">
          Run a new diagnostic →
        </Link>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: "#07080d", color: "#e8eef5" }}>
        <p className="text-sm text-white/50">Loading report…</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#07080d", cursor: "crosshair" }}>
      <div className="border-b border-white/[0.08] bg-[#07080d] px-4 py-3 text-center">
        <Link
          to="/doors/url-diagnostic"
          className="inline-block text-sm text-white/80 transition-colors hover:text-[#c9973a]"
        >
          <span className="text-[#c9973a]">This report was generated by Socialutely AnyDoor Engine</span>
          <span className="text-white/50"> · </span>
          <span className="underline decoration-[#c9973a]/50 underline-offset-4">Get your free diagnostic →</span>
        </Link>
      </div>
      <main className="mx-auto max-w-5xl px-4 py-8 sm:py-12 lg:max-w-6xl">
        <DiagnosticResults result={result} submittedUrl={submittedUrl} reportShareToken={normalizedToken} />
      </main>
    </div>
  );
}
