import Link from "next/link";
import { notFound } from "next/navigation";
import { DiagnosticResults } from "../../components/DiagnosticResults";
import { getProspectByShareToken, prospectRowToDiagnosticResult } from "../../lib/supabaseProspect";

export default async function SharedReportPage({ params }: { params: { token: string } }) {
  const token = params.token?.trim();
  if (!token) notFound();

  const row = await getProspectByShareToken(token);
  if (!row) notFound();

  const result = prospectRowToDiagnosticResult(row);
  if (!result) notFound();

  const submittedUrl = typeof row.url === "string" ? row.url : "";

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#07080d", cursor: "crosshair" }}>
      <div className="border-b border-white/[0.08] bg-[#07080d] px-4 py-3 text-center">
        <Link
          href="/"
          className="inline-block text-sm text-white/80 transition-colors hover:text-[#c9973a]"
        >
          <span className="text-[#c9973a]">This report was generated by Socialutely AnyDoor Engine</span>
          <span className="text-white/50"> · </span>
          <span className="underline decoration-[#c9973a]/50 underline-offset-4">Get your free diagnostic →</span>
        </Link>
      </div>
      <main className="mx-auto max-w-5xl px-4 py-8 sm:py-12 lg:max-w-6xl">
        <DiagnosticResults result={result} submittedUrl={submittedUrl} reportShareToken={token} />
      </main>
    </div>
  );
}
